/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 ./public/3d/starfighter.glb -T
Author: ChrisLee (https://sketchfab.com/chrisleeX)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-mandalorian-lego-n-1-starfighter-7681f18c7a6a4e5b860ece879bcb612c
Title: The Mandalorian - LEGO N 1 Starfighter
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function StarfighterModel(props) {
  const { nodes, materials } = useGLTF("./3d/starfighter-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Object513_SOLID-LIGHT_GRAY_0"].geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes["Object669_SOLID-DARK_GRAY_0"].geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes["Object748_SOLID-DARK_GRAY_0"].geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes["Object405_SOLID-DARK_GRAY_0"].geometry}
        material={materials.PaletteMaterial001}
        position={[-0.032, 0.266, 0.681]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["Object658_TRANS-CLEAR_0"].geometry}
        material={materials.PaletteMaterial002}
        position={[-0.028, 0.771, 1.52]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object714_Sticker_Rund_0.geometry}
        material={materials.Sticker_Rund}
        position={[1.247, 0.451, -0.636]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["Object730_TRANS-RED_0"].geometry}
        material={materials.PaletteMaterial003}
        position={[-0.032, 0.353, 0.075]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["Mandalorian-Logo_Mandalorian-Logo_0"].geometry}
        material={materials["Mandalorian-Logo"]}
        position={[0.392, 0.002, -1.402]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object001_sticker_3_0.geometry}
        material={materials.sticker_3}
        position={[-0.033, 0.683, 0]}
        rotation={[-Math.PI / 2, 0, 1.37]}
        scale={0.979}
      />
      <mesh
        geometry={nodes.Object002_sticker_4_0.geometry}
        material={materials.sticker_4}
        position={[-1.313, 0.659, -0.468]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/starfighter-transformed.glb");
